/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extrabonoloto;

import java.util.ArrayList;

/**
 *
 * @author aparcerozas
 */
public class Bonoloto extends javax.swing.JFrame {

    /**
     * Creates new form Bonoloto
     */
    private int contador = 0;
    private ArrayList<Integer> numeros = new ArrayList<>();
    private ArrayList<Integer> lista = new ArrayList<>();
    private int comprobar = 0;
    
    public Bonoloto() {
        initComponents();
    }
    
    public void mostrar(){
        textNos.setText("");
        for(Integer i : numeros){
            textNos.setText(textNos.getText().concat(i.toString()+","));
        }
    }
    
    public ArrayList<Integer> llenarArray(ArrayList<Integer> lista){
        for(int i=1;i<50;i++){
            lista.add(i);
        }
        return lista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        textNos = new javax.swing.JTextField();
        textRandom = new javax.swing.JTextField();
        textAcertos = new javax.swing.JTextField();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb7 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        cb9 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb11 = new javax.swing.JCheckBox();
        cb12 = new javax.swing.JCheckBox();
        cb13 = new javax.swing.JCheckBox();
        cb14 = new javax.swing.JCheckBox();
        cb15 = new javax.swing.JCheckBox();
        cb16 = new javax.swing.JCheckBox();
        cb17 = new javax.swing.JCheckBox();
        cb18 = new javax.swing.JCheckBox();
        cb19 = new javax.swing.JCheckBox();
        cb20 = new javax.swing.JCheckBox();
        cb21 = new javax.swing.JCheckBox();
        cb22 = new javax.swing.JCheckBox();
        cb23 = new javax.swing.JCheckBox();
        cb24 = new javax.swing.JCheckBox();
        cb25 = new javax.swing.JCheckBox();
        cb26 = new javax.swing.JCheckBox();
        cb27 = new javax.swing.JCheckBox();
        cb28 = new javax.swing.JCheckBox();
        cb29 = new javax.swing.JCheckBox();
        cb30 = new javax.swing.JCheckBox();
        cb31 = new javax.swing.JCheckBox();
        cb32 = new javax.swing.JCheckBox();
        cb33 = new javax.swing.JCheckBox();
        cb34 = new javax.swing.JCheckBox();
        cb35 = new javax.swing.JCheckBox();
        cb36 = new javax.swing.JCheckBox();
        cb37 = new javax.swing.JCheckBox();
        cb38 = new javax.swing.JCheckBox();
        cb39 = new javax.swing.JCheckBox();
        cb40 = new javax.swing.JCheckBox();
        cb41 = new javax.swing.JCheckBox();
        cb42 = new javax.swing.JCheckBox();
        cb43 = new javax.swing.JCheckBox();
        cb44 = new javax.swing.JCheckBox();
        cb45 = new javax.swing.JCheckBox();
        cb46 = new javax.swing.JCheckBox();
        cb47 = new javax.swing.JCheckBox();
        cb48 = new javax.swing.JCheckBox();
        cb49 = new javax.swing.JCheckBox();
        bComprobar = new javax.swing.JButton();
        bResetear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAcertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAcertosActionPerformed(evt);
            }
        });

        cb1.setText("1");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        cb2.setText("2");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb3.setText("3");
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });

        cb4.setText("4");
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });

        cb5.setText("5");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        cb6.setText("6");
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });

        cb7.setText("7");
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });

        cb8.setText("8");
        cb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb8ActionPerformed(evt);
            }
        });

        cb9.setText("9");
        cb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb9ActionPerformed(evt);
            }
        });

        cb10.setText("10");
        cb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb10ActionPerformed(evt);
            }
        });

        cb11.setText("11");
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });

        cb12.setText("12");
        cb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb12ActionPerformed(evt);
            }
        });

        cb13.setText("13");
        cb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb13ActionPerformed(evt);
            }
        });

        cb14.setText("14");
        cb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb14ActionPerformed(evt);
            }
        });

        cb15.setText("15");
        cb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb15ActionPerformed(evt);
            }
        });

        cb16.setText("16");
        cb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb16ActionPerformed(evt);
            }
        });

        cb17.setText("17");
        cb17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb17ActionPerformed(evt);
            }
        });

        cb18.setText("18");
        cb18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb18ActionPerformed(evt);
            }
        });

        cb19.setText("19");
        cb19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb19ActionPerformed(evt);
            }
        });

        cb20.setText("20");
        cb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb20ActionPerformed(evt);
            }
        });

        cb21.setText("21");
        cb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb21ActionPerformed(evt);
            }
        });

        cb22.setText("22");
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });

        cb23.setText("23");
        cb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb23ActionPerformed(evt);
            }
        });

        cb24.setText("24");
        cb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb24ActionPerformed(evt);
            }
        });

        cb25.setText("25");
        cb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb25ActionPerformed(evt);
            }
        });

        cb26.setText("26");
        cb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb26ActionPerformed(evt);
            }
        });

        cb27.setText("27");
        cb27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb27ActionPerformed(evt);
            }
        });

        cb28.setText("28");
        cb28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb28ActionPerformed(evt);
            }
        });

        cb29.setText("29");
        cb29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb29ActionPerformed(evt);
            }
        });

        cb30.setText("30");
        cb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb30ActionPerformed(evt);
            }
        });

        cb31.setText("31");
        cb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb31ActionPerformed(evt);
            }
        });

        cb32.setText("32");
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });

        cb33.setText("33");
        cb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb33ActionPerformed(evt);
            }
        });

        cb34.setText("34");
        cb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb34ActionPerformed(evt);
            }
        });

        cb35.setText("35");
        cb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb35ActionPerformed(evt);
            }
        });

        cb36.setText("36");
        cb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb36ActionPerformed(evt);
            }
        });

        cb37.setText("37");
        cb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb37ActionPerformed(evt);
            }
        });

        cb38.setText("38");
        cb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb38ActionPerformed(evt);
            }
        });

        cb39.setText("39");
        cb39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb39ActionPerformed(evt);
            }
        });

        cb40.setText("40");
        cb40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb40ActionPerformed(evt);
            }
        });

        cb41.setText("41");
        cb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb41ActionPerformed(evt);
            }
        });

        cb42.setText("42");
        cb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb42ActionPerformed(evt);
            }
        });

        cb43.setText("43");
        cb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb43ActionPerformed(evt);
            }
        });

        cb44.setText("44");
        cb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb44ActionPerformed(evt);
            }
        });

        cb45.setText("45");
        cb45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb45ActionPerformed(evt);
            }
        });

        cb46.setText("46");
        cb46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb46ActionPerformed(evt);
            }
        });

        cb47.setText("47");
        cb47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb47ActionPerformed(evt);
            }
        });

        cb48.setText("48");
        cb48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb48ActionPerformed(evt);
            }
        });

        cb49.setText("49");
        cb49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb49ActionPerformed(evt);
            }
        });

        bComprobar.setText("Comprobar");
        bComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bComprobarActionPerformed(evt);
            }
        });

        bResetear.setText("Resetear");
        bResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNos)
                            .addComponent(textRandom)
                            .addComponent(textAcertos, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb8)
                                .addGap(18, 18, 18)
                                .addComponent(cb9)
                                .addGap(18, 18, 18)
                                .addComponent(cb10)
                                .addGap(18, 18, 18)
                                .addComponent(cb11)
                                .addGap(18, 18, 18)
                                .addComponent(cb12)
                                .addGap(18, 18, 18)
                                .addComponent(cb13)
                                .addGap(18, 18, 18)
                                .addComponent(cb14))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb1)
                                .addGap(18, 18, 18)
                                .addComponent(cb2)
                                .addGap(18, 18, 18)
                                .addComponent(cb3)
                                .addGap(18, 18, 18)
                                .addComponent(cb4)
                                .addGap(18, 18, 18)
                                .addComponent(cb5)
                                .addGap(18, 18, 18)
                                .addComponent(cb6)
                                .addGap(18, 18, 18)
                                .addComponent(cb7))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb15)
                                .addGap(18, 18, 18)
                                .addComponent(cb16)
                                .addGap(18, 18, 18)
                                .addComponent(cb17)
                                .addGap(18, 18, 18)
                                .addComponent(cb18)
                                .addGap(18, 18, 18)
                                .addComponent(cb19)
                                .addGap(18, 18, 18)
                                .addComponent(cb20)
                                .addGap(18, 18, 18)
                                .addComponent(cb21))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb22)
                                .addGap(18, 18, 18)
                                .addComponent(cb23)
                                .addGap(18, 18, 18)
                                .addComponent(cb24)
                                .addGap(18, 18, 18)
                                .addComponent(cb25)
                                .addGap(18, 18, 18)
                                .addComponent(cb26)
                                .addGap(18, 18, 18)
                                .addComponent(cb27)
                                .addGap(18, 18, 18)
                                .addComponent(cb28))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb29)
                                .addGap(18, 18, 18)
                                .addComponent(cb30)
                                .addGap(18, 18, 18)
                                .addComponent(cb31)
                                .addGap(18, 18, 18)
                                .addComponent(cb32)
                                .addGap(18, 18, 18)
                                .addComponent(cb33)
                                .addGap(18, 18, 18)
                                .addComponent(cb34)
                                .addGap(18, 18, 18)
                                .addComponent(cb35))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb36)
                                .addGap(18, 18, 18)
                                .addComponent(cb37)
                                .addGap(18, 18, 18)
                                .addComponent(cb38)
                                .addGap(18, 18, 18)
                                .addComponent(cb39)
                                .addGap(18, 18, 18)
                                .addComponent(cb40)
                                .addGap(18, 18, 18)
                                .addComponent(cb41)
                                .addGap(18, 18, 18)
                                .addComponent(cb42))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(cb43)
                                .addGap(18, 18, 18)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(bComprobar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bResetear))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(cb44)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb45)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb46)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb47)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb48)))
                                .addGap(18, 18, 18)
                                .addComponent(cb49)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textNos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textAcertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb2)
                    .addComponent(cb3)
                    .addComponent(cb4)
                    .addComponent(cb5)
                    .addComponent(cb6)
                    .addComponent(cb7)
                    .addComponent(cb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb8)
                    .addComponent(cb9)
                    .addComponent(cb11)
                    .addComponent(cb12)
                    .addComponent(cb13)
                    .addComponent(cb14)
                    .addComponent(cb10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb15)
                    .addComponent(cb16)
                    .addComponent(cb17)
                    .addComponent(cb18)
                    .addComponent(cb19)
                    .addComponent(cb20)
                    .addComponent(cb21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb22)
                    .addComponent(cb23)
                    .addComponent(cb24)
                    .addComponent(cb25)
                    .addComponent(cb26)
                    .addComponent(cb27)
                    .addComponent(cb28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb30)
                    .addComponent(cb31)
                    .addComponent(cb32)
                    .addComponent(cb33)
                    .addComponent(cb34)
                    .addComponent(cb35)
                    .addComponent(cb29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb37)
                    .addComponent(cb38)
                    .addComponent(cb39)
                    .addComponent(cb40)
                    .addComponent(cb41)
                    .addComponent(cb42)
                    .addComponent(cb36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb44)
                    .addComponent(cb45)
                    .addComponent(cb47)
                    .addComponent(cb48)
                    .addComponent(cb49)
                    .addComponent(cb43)
                    .addComponent(cb46))
                .addGap(69, 69, 69)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComprobar)
                    .addComponent(bResetear))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textAcertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAcertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAcertosActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        if(cb1.isSelected()==true){
            if(contador<6){
                numeros.add(1);
                this.mostrar();
                contador++;
            }
            else{
                cb1.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==1){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        if(cb2.isSelected()==true){
            if(contador<6){
                numeros.add(2);
                this.mostrar();
                contador++;
            }
            else{
                cb2.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==2){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        if(cb3.isSelected()==true){
            if(contador<6){
                numeros.add(3);
                this.mostrar();
                contador++;
            }
            else{
                cb3.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==3){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb8ActionPerformed
        if(cb8.isSelected()==true){
            if(contador<6){
                numeros.add(8);
                this.mostrar();
                contador++;
            }
            else{
                cb8.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==8){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb8ActionPerformed

    private void cb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb9ActionPerformed
        if(cb9.isSelected()==true){
            if(contador<6){
                numeros.add(9);
                this.mostrar();
                contador++;
            }
            else{
                cb9.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==9){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb9ActionPerformed

    private void cb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb10ActionPerformed
        if(cb10.isSelected()==true){
            if(contador<6){
                numeros.add(10);
                this.mostrar();
                contador++;
            }
            else{
                cb10.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==10){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb10ActionPerformed

    private void cb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb15ActionPerformed
        if(cb15.isSelected()==true){
            if(contador<6){
                numeros.add(15);
                this.mostrar();
                contador++;
            }
            else{
                cb15.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==15){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb15ActionPerformed

    private void cb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb16ActionPerformed
        if(cb16.isSelected()==true){
            if(contador<6){
                numeros.add(16);
                this.mostrar();
                contador++;
            }
            else{
                cb16.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==16){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb16ActionPerformed

    private void cb17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb17ActionPerformed
        if(cb17.isSelected()==true){
            if(contador<6){
                numeros.add(17);
                this.mostrar();
                contador++;
            }
            else{
                cb17.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==17){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb17ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
        if(cb22.isSelected()==true){
            if(contador<6){
                numeros.add(22);
                this.mostrar();
                contador++;
            }
            else{
                cb22.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==22){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb22ActionPerformed

    private void cb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb23ActionPerformed
        if(cb23.isSelected()==true){
            if(contador<6){
                numeros.add(23);
                this.mostrar();
                contador++;
            }
            else{
                cb23.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==23){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb23ActionPerformed

    private void cb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb24ActionPerformed
        if(cb24.isSelected()==true){
            if(contador<6){
                numeros.add(24);
                this.mostrar();
                contador++;
            }
            else{
                cb24.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==24){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb24ActionPerformed

    private void cb29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb29ActionPerformed
        if(cb29.isSelected()==true){
            if(contador<6){
                numeros.add(29);
                this.mostrar();
                contador++;
            }
            else{
                cb29.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==29){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb29ActionPerformed

    private void cb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb30ActionPerformed
        if(cb30.isSelected()==true){
            if(contador<6){
                numeros.add(30);
                this.mostrar();
                contador++;
            }
            else{
                cb30.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==30){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb30ActionPerformed

    private void cb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb31ActionPerformed
        if(cb31.isSelected()==true){
            if(contador<6){
                numeros.add(31);
                this.mostrar();
                contador++;
            }
            else{
                cb31.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==31){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb31ActionPerformed

    private void cb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb36ActionPerformed
        if(cb36.isSelected()==true){
            if(contador<6){
                numeros.add(36);
                this.mostrar();
                contador++;
            }
            else{
                cb36.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==36){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb36ActionPerformed

    private void cb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb37ActionPerformed
        if(cb37.isSelected()==true){
            if(contador<6){
                numeros.add(37);
                this.mostrar();
                contador++;
            }
            else{
                cb37.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==37){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb37ActionPerformed

    private void cb38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb38ActionPerformed
        if(cb38.isSelected()==true){
            if(contador<6){
                numeros.add(38);
                this.mostrar();
                contador++;
            }
            else{
                cb38.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==38){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb38ActionPerformed

    private void cb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb43ActionPerformed
        if(cb43.isSelected()==true){
            if(contador<6){
                numeros.add(43);
                this.mostrar();
                contador++;
            }
            else{
                cb43.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==43){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb43ActionPerformed

    private void cb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb44ActionPerformed
        if(cb44.isSelected()==true){
            if(contador<6){
                numeros.add(44);
                this.mostrar();
                contador++;
            }
            else{
                cb44.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==44){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb44ActionPerformed

    private void cb45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb45ActionPerformed
        if(cb45.isSelected()==true){
            if(contador<6){
                numeros.add(45);
                this.mostrar();
                contador++;
            }
            else{
                cb45.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==45){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb45ActionPerformed

    private void cb19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb19ActionPerformed
        if(cb19.isSelected()==true){
            if(contador<6){
                numeros.add(19);
                this.mostrar();
                contador++;
            }
            else{
                cb19.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==19){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb19ActionPerformed

    private void cb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb34ActionPerformed
        if(cb34.isSelected()==true){
            if(contador<6){
                numeros.add(34);
                this.mostrar();
                contador++;
            }
            else{
                cb34.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==34){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb34ActionPerformed

    private void cb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb41ActionPerformed
        if(cb41.isSelected()==true){
            if(contador<6){
                numeros.add(41);
                this.mostrar();
                contador++;
            }
            else{
                cb41.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==41){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb41ActionPerformed

    private void cb46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb46ActionPerformed
        if(cb46.isSelected()==true){
            if(contador<6){
                numeros.add(46);
                this.mostrar();
                contador++;
            }
            else{
                cb46.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==46){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb46ActionPerformed

    private void cb48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb48ActionPerformed
        if(cb48.isSelected()==true){
            if(contador<6){
                numeros.add(48);
                this.mostrar();
                contador++;
            }
            else{
                cb48.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==48){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb48ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        if(cb4.isSelected()==true){
            if(contador<6){
                numeros.add(4);
                this.mostrar();
                contador++;
            }
            else{
                cb4.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==4){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        if(cb5.isSelected()==true){
            if(contador<6){
                numeros.add(5);
                this.mostrar();
                contador++;
            }
            else{
                cb5.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==5){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        if(cb6.isSelected()==true){
            if(contador<6){
                numeros.add(6);
                this.mostrar();
                contador++;
            }
            else{
                cb6.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==6){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
        if(cb7.isSelected()==true){
            if(contador<6){
                numeros.add(7);
                this.mostrar();
                contador++;
            }
            else{
                cb7.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==7){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb7ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
        if(cb11.isSelected()==true){
            if(contador<6){
                numeros.add(11);
                this.mostrar();
                contador++;
            }
            else{
                cb11.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==11){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb11ActionPerformed

    private void cb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb12ActionPerformed
        if(cb12.isSelected()==true){
            if(contador<6){
                numeros.add(12);
                this.mostrar();
                contador++;
            }
            else{
                cb12.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==12){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb12ActionPerformed

    private void cb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb13ActionPerformed
        if(cb13.isSelected()==true){
            if(contador<6){
                numeros.add(13);
                this.mostrar();
                contador++;
            }
            else{
                cb13.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==13){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb13ActionPerformed

    private void cb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb14ActionPerformed
        if(cb14.isSelected()==true){
            if(contador<6){
                numeros.add(14);
                this.mostrar();
                contador++;
            }
            else{
                cb14.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==14){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb14ActionPerformed

    private void cb18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb18ActionPerformed
        if(cb18.isSelected()==true){
            if(contador<6){
                numeros.add(18);
                this.mostrar();
                contador++;
            }
            else{
                cb18.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==18){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb18ActionPerformed

    private void cb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb20ActionPerformed
        if(cb20.isSelected()==true){
            if(contador<6){
                numeros.add(20);
                this.mostrar();
                contador++;
            }
            else{
                cb20.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==20){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb20ActionPerformed

    private void cb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb21ActionPerformed
        if(cb21.isSelected()==true){
            if(contador<6){
                numeros.add(21);
                this.mostrar();
                contador++;
            }
            else{
                cb21.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==21){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb21ActionPerformed

    private void cb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb25ActionPerformed
        if(cb25.isSelected()==true){
            if(contador<6){
                numeros.add(25);
                this.mostrar();
                contador++;
            }
            else{
                cb25.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==25){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb25ActionPerformed

    private void bComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bComprobarActionPerformed
        textRandom.setText("");
        lista.removeAll(lista);
        comprobar=0;
        lista = this.llenarArray(lista);
        for(int i=0;i<6;i++){
            int random = (int)Math.floor(Math.random()*50);
            for(int j=0;j<lista.size();j++){
                if(random==lista.get(j)){
                    textRandom.setText(textRandom.getText().concat(random + ","));
                    lista.remove(j);
                    comprobar = 1;
                }
            }
            if(comprobar==0){
                i=i-1;
            }
            comprobar=0;
        }
        int aciertos = 0;
        String[] comprobar1 = textNos.getText().split(",");
        String[] comprobar2 = textRandom.getText().split(",");
        for (String num1 : comprobar1) {
            for (String num2 : comprobar2) {
                if(num1.equals(num2)){
                    aciertos++;
                }
            }
        }
        textAcertos.setText("Número de aciertos: " + aciertos);
    }//GEN-LAST:event_bComprobarActionPerformed

    private void bResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetearActionPerformed
        textRandom.setText("");
        lista.removeAll(lista);
        comprobar=0;
    }//GEN-LAST:event_bResetearActionPerformed

    private void cb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb26ActionPerformed
        if(cb26.isSelected()==true){
            if(contador<6){
                numeros.add(26);
                this.mostrar();
                contador++;
            }
            else{
                cb26.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==26){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb26ActionPerformed

    private void cb27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb27ActionPerformed
        if(cb27.isSelected()==true){
            if(contador<6){
                numeros.add(27);
                this.mostrar();
                contador++;
            }
            else{
                cb27.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==27){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb27ActionPerformed

    private void cb28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb28ActionPerformed
        if(cb28.isSelected()==true){
            if(contador<6){
                numeros.add(28);
                this.mostrar();
                contador++;
            }
            else{
                cb28.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==28){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb28ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
        if(cb32.isSelected()==true){
            if(contador<6){
                numeros.add(32);
                this.mostrar();
                contador++;
            }
            else{
                cb32.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==32){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb32ActionPerformed

    private void cb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb33ActionPerformed
        if(cb33.isSelected()==true){
            if(contador<6){
                numeros.add(33);
                this.mostrar();
                contador++;
            }
            else{
                cb33.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==33){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb33ActionPerformed

    private void cb35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb35ActionPerformed
        if(cb35.isSelected()==true){
            if(contador<6){
                numeros.add(35);
                this.mostrar();
                contador++;
            }
            else{
                cb35.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==35){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb35ActionPerformed

    private void cb39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb39ActionPerformed
        if(cb39.isSelected()==true){
            if(contador<6){
                numeros.add(39);
                this.mostrar();
                contador++;
            }
            else{
                cb39.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==39){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb39ActionPerformed

    private void cb40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb40ActionPerformed
        if(cb40.isSelected()==true){
            if(contador<6){
                numeros.add(40);
                this.mostrar();
                contador++;
            }
            else{
                cb40.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==40){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb40ActionPerformed

    private void cb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb42ActionPerformed
        if(cb42.isSelected()==true){
            if(contador<6){
                numeros.add(42);
                this.mostrar();
                contador++;
            }
            else{
                cb42.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==42){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb42ActionPerformed

    private void cb47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb47ActionPerformed
        if(cb47.isSelected()==true){
            if(contador<6){
                numeros.add(47);
                this.mostrar();
                contador++;
            }
            else{
                cb47.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==47){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb47ActionPerformed

    private void cb49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb49ActionPerformed
        if(cb49.isSelected()==true){
            if(contador<6){
                numeros.add(49);
                this.mostrar();
                contador++;
            }
            else{
                cb49.setSelected(false);
            }
        }
        else{
            for (int i = 0; i < numeros.size(); i++) {
                if(numeros.get(i)==49){
                    numeros.remove(i);
                }
            }
            this.mostrar();
            contador--;
        }
    }//GEN-LAST:event_cb49ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bonoloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bComprobar;
    private javax.swing.JButton bResetear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb12;
    private javax.swing.JCheckBox cb13;
    private javax.swing.JCheckBox cb14;
    private javax.swing.JCheckBox cb15;
    private javax.swing.JCheckBox cb16;
    private javax.swing.JCheckBox cb17;
    private javax.swing.JCheckBox cb18;
    private javax.swing.JCheckBox cb19;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb20;
    private javax.swing.JCheckBox cb21;
    private javax.swing.JCheckBox cb22;
    private javax.swing.JCheckBox cb23;
    private javax.swing.JCheckBox cb24;
    private javax.swing.JCheckBox cb25;
    private javax.swing.JCheckBox cb26;
    private javax.swing.JCheckBox cb27;
    private javax.swing.JCheckBox cb28;
    private javax.swing.JCheckBox cb29;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb30;
    private javax.swing.JCheckBox cb31;
    private javax.swing.JCheckBox cb32;
    private javax.swing.JCheckBox cb33;
    private javax.swing.JCheckBox cb34;
    private javax.swing.JCheckBox cb35;
    private javax.swing.JCheckBox cb36;
    private javax.swing.JCheckBox cb37;
    private javax.swing.JCheckBox cb38;
    private javax.swing.JCheckBox cb39;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb40;
    private javax.swing.JCheckBox cb41;
    private javax.swing.JCheckBox cb42;
    private javax.swing.JCheckBox cb43;
    private javax.swing.JCheckBox cb44;
    private javax.swing.JCheckBox cb45;
    private javax.swing.JCheckBox cb46;
    private javax.swing.JCheckBox cb47;
    private javax.swing.JCheckBox cb48;
    private javax.swing.JCheckBox cb49;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JCheckBox cb9;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField textAcertos;
    private javax.swing.JTextField textNos;
    private javax.swing.JTextField textRandom;
    // End of variables declaration//GEN-END:variables
}
